
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileWriter;
import java.util.Random;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
//import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NCM
 */
public class frame4 extends javax.swing.JFrame {

    /**
     * Creates new form frame4
     */
    public frame4() {
        initComponents();
         setTitle("ADMISSION INFO SYSTEM");
         middle();
    }
    public void middle(){
        setLocationRelativeTo(null);
    }
     public void close(){
 
         WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
         Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
 
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        frame4_fname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        frame4_sname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        frame4_date = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        frame4_male = new javax.swing.JCheckBox();
        frame4_female = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        frame4_addr = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        frame4_email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        frame4_mobile = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        frame4_ssc = new javax.swing.JTextField();
        frame4_hsc = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        farme4_submit = new javax.swing.JButton();
        frame4_sscyear = new javax.swing.JTextField();
        frame4_hscyear = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 800));

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("APPLICATION FORM");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        frame4_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frame4_fnameActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel2.setText("FIRST NAME");

        jLabel3.setBackground(new java.awt.Color(204, 204, 255));
        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel3.setText("SECOND NAME");

        jLabel4.setBackground(new java.awt.Color(204, 204, 255));
        jLabel4.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel4.setText("DATE OF BIRTH");

        frame4_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frame4_dateActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel5.setText("GENDER");

        frame4_male.setText("male");
        frame4_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frame4_maleActionPerformed(evt);
            }
        });

        frame4_female.setText("Female");
        frame4_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frame4_femaleActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(204, 204, 255));
        jLabel6.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel6.setText("ADDRESS");

        frame4_addr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frame4_addrActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(204, 204, 255));
        jLabel7.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel7.setText("EMAIL_ID");

        jLabel8.setBackground(new java.awt.Color(204, 204, 255));
        jLabel8.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel8.setText("MOBIL NO");

        frame4_mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frame4_mobileActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(204, 204, 255));
        jLabel10.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel10.setText("SSC RESULT");

        jLabel12.setBackground(new java.awt.Color(204, 204, 255));
        jLabel12.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel12.setText("YEAR");

        frame4_ssc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frame4_sscActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(204, 204, 255));
        jLabel13.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel13.setText("YEAR");

        farme4_submit.setBackground(new java.awt.Color(0, 153, 153));
        farme4_submit.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        farme4_submit.setForeground(new java.awt.Color(51, 0, 51));
        farme4_submit.setText("SUBMIT");
        farme4_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                farme4_submitActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(204, 204, 255));
        jLabel11.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel11.setText("HSC RESULT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(farme4_submit)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(frame4_fname, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                    .addComponent(frame4_sname)
                                    .addComponent(frame4_date)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(frame4_addr, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(frame4_male)
                                        .addGap(18, 18, 18)
                                        .addComponent(frame4_female))
                                    .addComponent(frame4_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(frame4_hsc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                                .addComponent(frame4_ssc, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel12)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(frame4_sscyear, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel13)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(frame4_hscyear))))
                                        .addComponent(frame4_email, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addContainerGap(420, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frame4_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(frame4_sname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(frame4_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(frame4_male)
                    .addComponent(frame4_female))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(frame4_addr, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frame4_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frame4_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frame4_ssc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(frame4_sscyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(frame4_hsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(frame4_hscyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(farme4_submit))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void farme4_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_farme4_submitActionPerformed
        // TODO add your handling code here:
        String firstname=frame4_fname.getText().toString();
        String Secondname=frame4_sname.getText().toString();
        String date=frame4_date.getText().toString();
        //String gender=frame4_male.getText().toString(); 
       //String gender1=frame4_female.getText().toString();
        String add=frame4_addr.getText().toString();
        String email=frame4_email.getText().toString();
        String mobile=frame4_mobile.getText().toString();
        
        String ssc=frame4_ssc.getText().toString();
        String hsc=frame4_hsc.getText().toString();
        String year1=frame4_sscyear.getText().toString();
        String year2=frame4_hscyear.getText().toString();
         Random randomNum = new Random();
        int min = 1;
        int max = 100;
        int x = randomNum.nextInt(max) + min;
       String m = "male";
       String f = "female";
     
       try {
          FileWriter writer=new  FileWriter ("admission.txt",true);
          FileWriter writer2=new  FileWriter ("name.txt",true);
          FileWriter writer1=new  FileWriter ("pending.txt",true);
           String s = String.valueOf(x);
           writer.write(s);
           writer.write(" ");
           writer2.write(firstname);
           writer2.close();
           writer1.write(firstname);
           writer.write(System.lineSeparator());
           writer1.write(System.lineSeparator());
           writer.write(Secondname);
           writer1.write(Secondname);
           writer.write(System.lineSeparator());
           writer1.write(System.lineSeparator());
           writer.write(date);
           writer1.write(date);
           writer.write(System.lineSeparator());
           writer1.write(System.lineSeparator());
           //writer.write(gender);
           //writer.write(System.getProperty("line.separater"));
           //writer.write(gender1);
                if(frame4_male.isSelected())
                  {
                     writer.write(m);
                     writer1.write(m);
                     writer.write(System.lineSeparator());
                     //writer1.write(System.lineSeparator());  
                  }
                else
               {   
                   writer.write(f);
                   writer1.write(f);
                // writer.write(System.getProperty("line.separater"));
                }
           writer.write(System.lineSeparator());
            writer1.write(System.lineSeparator());
            writer.write(add);
            writer1.write(add);
           writer.write(System.lineSeparator());
           writer1.write(System.lineSeparator());
            writer.write(email);
            writer1.write(email);
          writer.write(System.lineSeparator());
          writer1.write(System.lineSeparator());
            writer.write(mobile);
             writer1.write(mobile);
            writer.write(System.lineSeparator());
            writer1.write(System.lineSeparator());
           
            writer.write(ssc);
            writer1.write(ssc);
           writer.write(System.lineSeparator());
            writer1.write(System.lineSeparator());
            writer.write(hsc);
             writer1.write(hsc);
            writer.write(System.lineSeparator());
             writer1.write(System.lineSeparator());
           writer.write(year1);
             writer1.write(year1);
           writer.write(System.lineSeparator());
           writer1.write(System.lineSeparator());
            writer.write(year2);
            writer1.write(year2);
            try{
           writer.write(System.lineSeparator());
            }catch(Exception e){
             JOptionPane.showMessageDialog(rootPane, "error43");
            }
              writer.close();
              writer1.close();
            JOptionPane.showMessageDialog(rootPane, "Success");
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "error");
        }
       close();
        frame7 Info=new frame7();
        Info.setVisible(true);
        
        
        
        
    }//GEN-LAST:event_farme4_submitActionPerformed

    private void frame4_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frame4_fnameActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_frame4_fnameActionPerformed

    private void frame4_sscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frame4_sscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frame4_sscActionPerformed

    private void frame4_mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frame4_mobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frame4_mobileActionPerformed

    private void frame4_addrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frame4_addrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frame4_addrActionPerformed

    private void frame4_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frame4_femaleActionPerformed
         if (frame4_female.isSelected()) {
            frame4_male.setEnabled(false);
           
        } else {
           frame4_male.setEnabled(true);
           frame4_female.setEnabled(true);
           
        }
    }//GEN-LAST:event_frame4_femaleActionPerformed

    private void frame4_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frame4_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frame4_dateActionPerformed

    private void frame4_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frame4_maleActionPerformed
        // TODO add your handling code here:
         if (frame4_male.isSelected()) {
            frame4_female.setEnabled(false);
           
        } else {
           frame4_male.setEnabled(true);
           frame4_female.setEnabled(true);
           
        }

    }//GEN-LAST:event_frame4_maleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton farme4_submit;
    private javax.swing.JTextField frame4_addr;
    private javax.swing.JTextField frame4_date;
    private javax.swing.JTextField frame4_email;
    private javax.swing.JCheckBox frame4_female;
    private javax.swing.JTextField frame4_fname;
    private javax.swing.JTextField frame4_hsc;
    private javax.swing.JTextField frame4_hscyear;
    private javax.swing.JCheckBox frame4_male;
    private javax.swing.JTextField frame4_mobile;
    private javax.swing.JTextField frame4_sname;
    private javax.swing.JTextField frame4_ssc;
    private javax.swing.JTextField frame4_sscyear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
